### ISSUE TITLE
Replace _glob() with a simpler function

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#10]
Currently, a `Backend` class needs to implement a `_glob()` function, which according docstring has to be able to scan into sub-directories and support wildcards. Implementing it for `Artifactory` and `FileSystem` was quite simple, but for other backends we might implement in the future it might become tricky. So I wonder if we should replace it with a simpler function that only returns the file names of a directory (and maybe another one that returns sub-directories). If we want to support recursive search and wildcards, we should implement this in `Backend.glob()` based on this simpler function(s).

**Comment by hagenw** [comment]
A first step to replace `glob()` would be to add a method that allows to list the content of a folder on the backend. 

I'm not sure if this will speed `audb.available()` up for Artifactory as we would have to first get a list of all databases and then for each database a list of all versions. But at least we could try as the current solution using `glob()` is also not very fast:

```python
>>> timeit.timeit("df = audb.available()", number=1, setup="import audb")
60.44373281300068
```

**Comment by frankenjoe** [comment]
> A first step to replace `glob()` would be to add a method that allows to list the content of a folder on the backend.

Sounds like a plan :)

**Comment by frankenjoe** [comment]
I'd like to pick up this topic again. Reason: I have implemented a backend for [Google Cloud Storage](https://cloud.google.com/storage), which was straight-forward except for the `glob` function. We could implement it [like this](https://gist.github.com/agraubert/e3a5c4e4897aacbed82559453da128a8), but I think on the long run it's better if we don't force users to implement a complex backend function like `glob`.

The question is how we should proceed now. I see two options:

1. deprecate and remove at some point, new backends are not required to implement it
2. Implement glob in `Backend` using some simpler functions provided by the derived classes (e.g. this is the implementation in [cpython](https://github.com/python/cpython/blob/main/Lib/glob.py)

At the moment I'm more leaning towards 1 and instead of `glob` introduce something similar like [audeer.list_file_names()](https://github.com/audeering/audeer/blob/9798923c7ef1f8dfdadce6e21c65678688fcd6aa/audeer/core/io.py#L398) and [audeer.list_dir_names()](https://github.com/audeering/audeer/blob/9798923c7ef1f8dfdadce6e21c65678688fcd6aa/audeer/core/io.py#L338). Internally those functions only depend on `os.listdir()`, `os.path.isdir()` and `fnmatch()`. Since we already have [ls()](https://audeering.github.io/audbackend/api.html#audbackend.Backend.ls), we only have to introduce a new abstract method `Backend.isdir()` to achieve this.

**Comment by hagenw** [comment]
I agree, that it will make it much easier to add other backends (especially from the web) if we require only simple functions.

I also think that as long as we don't have immediate need for a `glob()` function, I would not add it and instead start with something similar to `list_dir_names` and `list_file_names`. The only question is then if we should make it even easier and say we don't support hidden files as not all backends might support them?

**Comment by hagenw** [comment]
BTW, if we have already `ls()` do we need anything on top at all, or could still deprecate and remove `glob()`?

**Comment by frankenjoe** [comment]
> BTW, if we have already `ls()` do we need anything on top at all, or could still deprecate and remove `glob()`?

As I pointed out before I think we also need `isdir()` if we want to implement something similar to `list_dir_names()` and `list_file_names()` as we have in `audeer`. But I think that's it.

**Comment by frankenjoe** [comment]
> The only question is then if we should make it even easier and say we don't support hidden files as not all backends might support them?

I think it's enough if we simply return all files, the user can still filter files afterwards.
