### ISSUE TITLE
Store MD5 sums on backends that don't support that?

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#113]
We use MD5 sums in order to check if a local file and a file on the backend are the same, e.g. https://github.com/audeering/audbackend/pull/111. The Artifactory backend has support for storing the MD5 sum directly in the backend and when calling `backend.checksum(path)` it is just returned and does not need to be calculated. This is different for the `file-system` backend where the sum needs to be re-calculated every time. Maybe we can come up with a solution that manually stores the MD5 sums on the backend as well for all backends that have no native support for it.

**Comment by frankenjoe** [comment]
I guess there are two options: store the checksum in an additional file, e.g. <file>.md5 next to the original file. Or keep a table in the repository that stores the checksum for every file. However, as you already mentioned some backends like Artifactory provide a built-in way to store the checksum. So in that case the information would be stored twice. So I think I would leave it to the backend to store the checksum or not. For file-system I am not sure if it is really needed since calculating the checksum should be relatively fast as there is no need to download the file from a server first.

**Comment by hagenw** [comment]
For the new `minio` backend we indeed decided to implement this functionality directly in the backend. So there is no additional overhead needed at the moment, and I will close this issue.
