### ISSUE TITLE
Add possibility to store backend settings on the backend

### ISSUE THREAD

**Issue by hagenw** [audeering/audbackend#166]
In #155 we want to introduce support for backends without versioning, and we have already the case of backends storing file in a legacy mode. This means when accessing a `FileSystem` backend the user needs to know if it is a legacy backend or not.

If we find a way to store backend settings on the backend, we could easily add `versioning` as an argument when creating a new backend and store the setting on the backend (and the same with legacy file structure). Of cause, if the code accessing the backend requires a legacy file structure or versioning it has to throw an error if it is not available.

**Comment by frankenjoe** [comment]
The solution I currently have in mind for #155 would not require to distinguish between a non-versioned and a versioned backend. It would simply allow setting `version=None` and in that case store a file under `/sub/file.txt` instead of `/sub/<version>/file.txt`. For legacy backends we probably want to forbid `version=None`.

**Comment by hagenw** [comment]
But if you don't distinguish, it means you can mix storing versioned and non-versioned files on a backend. Do we want to have this?

**Comment by frankenjoe** [comment]
I don't really see an issue with that. In most use-cases, `audbackend` is anyway used under the hood of another package, which actually takes care about the versioning. And from a user perspective it can even be a feature that you can mix non-versioned files and versioned files. E.g. for some files in your repository you don't need to keep a history, e.g. cached files. While other files, you want to version. And even if you have stored a file without version, you can still start a history by storing the next file with a version. When you do `backend.ls('/sub/file.txt')` you would then get `[('/sub/file.txt', None), ('/sub/file.txt', '1.0.0'), ...)]`. So in some sense even a non-versioned file still has the version `None` and can be clearly distinguished from files with a version.

**Comment by hagenw** [comment]
Makes sense.

I think you might still be able to also handle backend that support only one of two options (e.g. imagine a backend that cannot handle folders and always needs a version number for a file. In that case you can just raise an error if `version=None`.)

**Comment by frankenjoe** [comment]
Yes, we could add an option that forbids `version=None` of course.

**Comment by frankenjoe** [comment]
I started to implement the `version=None` solution, and it's indeed straight-forward to implement without only minor changes. However, there is one problem - so far we make no assumption about `version`, except that is has to be non-empty and must not contain certain characters like `?`. I.e. a user can do:

```python
backend.put_file(file, '/file.txt', 'sub')
backend.ls()
```
```
[('/file.txt', 'sub')]
```

Now, if we allow version to be `None`, we can not distinguish between `/file.txt` with version `'sub'` and `/sub/file.txt`:

```python
backend.put_file(file, '/sub/file.txt')  # version = None
backend.ls()
```
```
[('/file.txt', 'sub')]
```

While the expected output would be:

```
[('/sub/file.txt', None)]
```

But therefore we would need to have a way to check if a sub-directory is a version or not.

I see two solutions:

1. We restrict version to follow a certain format.
2. We implement two interfaces, e.g. `Backend` and `VersionedBackend`. The difference between the two interface is that `VersionedBackend` provides an additional `version` parameter to all functions. Which one will be used is then controlled via parameter we add to `audbackend.create()` / `audbackend.access()`.

Since 1. would be a breaking change, I will look into 2. first that we see how it feels.

**Comment by frankenjoe** [comment]
Continue discussion in https://github.com/audeering/audbackend/issues/155

**Comment by hagenw** [comment]
We solved this by introducing the concept of interfaces instead. An interface can take care of storing different versions of a file on the backend. As we don't want to restrict accessing a backend by a single interface, we decided to not store any settings on the backend itself.
