### ISSUE TITLE
Fix audbackend.Backend interface

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#46]
As discussed in https://github.com/audeering/audbackend/issues/40 there are two problems with the current backend interface.

1. The method `Backend.path()` assumes there is a deterministic way to convert a virtual path to a backend path. This is probably too restrictive. E.g. think of a backend which assigns a random ID to a file when it is uploaded.
2. The method `Backend.ls()` takes as input a folder in the backend format. But this assumes that the concept of a folder exists for every backend, which is again too restrictive. E.g. think of a backend where files are stored in a database under some key.

To overcome these issues I propose we do the following:

- [x] Remove the method `Backend.path()` and the according abstract method `Backend._path()`. Instead we forward the virtual path to all abstract functions. ~~For backward compatibility we implement `FileSystem.path()` and `Artifactory.path()` directly in the child class.~~. See https://github.com/audeering/audbackend/pull/47
- [x] Fix `Backend.ls()` that it accepts a folder in virtual format. ~~The current implementation is a bug, but maybe we still want to implement `FileSystem.ls()` and `Artifactory.ls()` for backward compatibility and choose a new method name.~~, see https://github.com/audeering/audbackend/pull/53
- [x] Remove `Backend.glob()`, see https://github.com/audeering/audbackend/pull/79
- [x] Implement a backend without folders and randomly generated file names to verify the interface supports such a backend now

**Comment by frankenjoe** [comment]
@hagenw I might dedicate some time to work on this, but wanted to get your feedback first if you agree the suggested approach makes sense.

**Comment by hagenw** [comment]
Regarding `Backend.path()` I slightly disagree. I think we need a deterministic way to get a path, otherwise we will not be able to find a file again on the backend. Converting the virtual path can be done by a random process, but then we need to have a mapping/database that stores the connection between the virtual path and the actual path on the backend.
But it might be that a user would never need `Backend.path()`, then we could indeed remove it. But then I would also remove `FileSystem.path()` and `Artifactory.path()`.

I would indeed change the behavior of `Backend.ls()`, and think it should also be fine to add breaking changes to `FileSystem.ls()` and `Artifactory.ls()` and update packages where we use this code to the new behavior.

**Comment by frankenjoe** [comment]
> Converting the virtual path can be done by a random process, but then we need to have a mapping/database that stores the connection between the virtual path and the actual path on the backend.

Sure, but that lies in the responsibility of the backend implementation.

> But it might be that a user would never need Backend.path(), then we could indeed remove it. But then I would also remove FileSystem.path() and Artifactory.path().

Good, I'm also fine with removing it.

> I would indeed change the behavior of Backend.ls(), and think it should also be fine to add breaking changes to FileSystem.ls() and Artifactory.ls() and update packages where we use this code to the new behavior.

Ok.

**Comment by frankenjoe** [comment]
We have now implemented all steps outlined in the description so I will consider this issue as solved.
