### ISSUE TITLE
Ensure backend paths start with `/`

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#57]
In #53 we define that the root of a backend as `/`. Accordingly we should ensure that a backend path always starts with `/`. For backward compatibility I suggest we do this in `utils.check_path_and_ext()`.

**Comment by hagenw** [comment]
Mh, maybe I was to strong requesting `/` for the root of the backend, because you cannot ask for relative paths anyway, can you?
So there should be no difference between `/folder/file.ext` and `path/file.ext`.

On the other you are also right, starting always with `/` makes it more obvious that we are dealing with the root of the backend here.

**Comment by frankenjoe** [comment]
Yes, I suggest we accept both (`/folder/file.ext` and `folder/file.ext`), but internally always convert to `/folder/file.ext`.

**Comment by hagenw** [comment]
OK

**Comment by frankenjoe** [comment]
Since we will anyway introduce some breaking changes I would propose that we now enforce that a backend path has to start with `'/'`. So far we have no use-case for relative paths, but maybe someday and then it's easier to implement when we now ensure all paths are passed as absolute paths.

**Comment by frankenjoe** [comment]
@hagenw before I start working on a PR, do you agree with my suggestion to enforce `'/'`?

**Comment by hagenw** [comment]
Yes, I think it makes indeed more future proof to require `/` when referring to an absolute path, even though we don't have any method that supports a relative path yet.
